/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VeIncident: typeof import('./src/components/ve-page/ve-incident/index.vue')['default']
    VePage: typeof import('./src/components/ve-page/index.vue')['default']
    VeSlots: typeof import('./src/components/ve-page/ve-slots/index.vue')['default']
    VeStats: typeof import('./src/components/ve-page/ve-stats/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
